name: CI

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        repository: matplotlib/mpl-docker
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built images
      run: docker images
    - name: Clone matplotlib
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: matplotlib/matplotlib
        path: matplotlib
    - name: Build matplotlib docs
      if: success() && github.event_name == 'push'
      run: >-
        docker run --rm
        -v $PWD/matplotlib/:/mpl_source
        -w /mpl_source
        matplotlib/mpl-docker:test
        /bin/bash -c 'python -m pip install . && make -C/mpl_source/doc html'
      # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    - name: Deploy docs to GitHub Pages
      if: success() && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: matplotlib/doc/build/html
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: Deploy to GitHub pages
