name: CI

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        repository: matplotlib/mpl-docker
        dockerfile: Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List built images
      run: docker images
    - name: Clone matplotlib
      uses: actions/checkout@v2
      with:
        repository: matplotlib/matplotlib
        path: matplotlib
    - name: Build matplotlib docs
      run: >-
        docker run --rm
        -v $PWD/matplotlib/:/mpl_source
        -w /mpl_source
        matplotlib/mpl-docker:test
        /bin/bash -c 'python -m pip install . && make -C/mpl_source/doc html'
